spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.128.211:3306/xuecheng_system?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: "015610"
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

